"""
Regenerate public/favicon.svg from the site's display face.

The favicon has to be the CSJACKO wordmark in Groovy Madness, and an SVG used
as a favicon renders in a restricted mode with no access to webfonts: naming the
family there falls through to a system sans. So the glyphs are converted to real
outlines and baked into the file as paths.

Run after changing the display font or the mark:

    python3 scripts/make-favicon.py

Needs fonttools and brotli (brotli is what reads woff2):

    pip3 install fonttools brotli
"""

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

FONT = 'src/assets/fonts/groovy-madness.woff2'
OUT = 'public/favicon.svg'
BOX, PAD, GAP = 64, 4.5, 3.0
LINES = ('CS', 'JACKO')
BG, FG = '#000000', '#e62317'

# Two decimals. Groovy's melted contours carry a lot of points, and at full
# float precision the file lands around 56KB, which is absurd for an icon drawn
# at 16px. Rounding is invisible at any size a favicon is seen and cuts it by
# roughly four fifths.
PRECISION = 2

font = TTFont(FONT)
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
hmtx = font['hmtx']


def fmt(n):
    return f'{round(n, PRECISION):g}'


def measure(text):
    """Bounds of a word laid out with its real advances."""
    bounds, x = None, 0
    for ch in text:
        g = cmap[ord(ch)]
        pen = BoundsPen(glyphs)
        glyphs[g].draw(pen)
        if pen.bounds:
            x0, y0, x1, y1 = pen.bounds
            b = (x0 + x, y0, x1 + x, y1)
            bounds = b if bounds is None else (
                min(bounds[0], b[0]), min(bounds[1], b[1]),
                max(bounds[2], b[2]), max(bounds[3], b[3]))
        x += hmtx[g][0]
    return bounds


def line_path(text, scale, dx, dy):
    """One path for a whole word, flipped from font space into SVG space."""
    parts, x = [], 0.0
    for ch in text:
        g = cmap[ord(ch)]
        pen = SVGPathPen(glyphs, ntos=fmt)
        glyphs[g].draw(
            TransformPen(pen, Transform(scale, 0, 0, -scale, dx + x * scale, dy))
        )
        parts.append(pen.getCommands())
        x += hmtx[g][0]
    return ' '.join(p for p in parts if p)


usable = BOX - PAD * 2
rows = []
for text in LINES:
    x0, y0, x1, y1 = measure(text)
    scale = usable / (x1 - x0)
    rows.append(dict(text=text, x0=x0, y0=y0, scale=scale, h=(y1 - y0) * scale))

y = (BOX - (rows[0]['h'] + GAP + rows[1]['h'])) / 2
paths = []
for r in rows:
    s = r['scale']
    paths.append(line_path(r['text'], s, PAD - r['x0'] * s, y + r['h'] + r['y0'] * s))
    y += r['h'] + GAP

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}" role="img" aria-label="CSJACKO">
  <!-- Generated by scripts/make-favicon.py. Do not hand-edit.

       Real Groovy Madness outlines, not text in a font-family: an SVG favicon
       renders with no access to webfonts, so a named family would fall through
       to a system sans and stop matching the site.

       Two lines because a favicon is seen at 16 to 32px, where CSJACKO across a
       single line solves to about 7px a letter. Each line is scaled on its own
       to fill the width, which is why CS sets larger than JACKO. -->
  <rect width="{BOX}" height="{BOX}" fill="{BG}"/>
  <g fill="{FG}">
    <path d="{paths[0]}"/>
    <path d="{paths[1]}"/>
  </g>
</svg>
'''
open(OUT, 'w').write(svg)
print(f'{OUT}: {len(svg):,} bytes')
